### ISSUE TITLE
HW acceleration features are gone

### ISSUE THREAD

**Issue by ghost** [RPi-Distro/chromium-browser#47] opened 2024-09-12 22:12 UTC
After the latest updates which included the name change of chromium-browser (i think it will be called chromium from now on), i have lost hw acceleration, completely.

![screenshot](https://github.com/user-attachments/assets/cabc0f52-3158-4a04-bc5e-a2117a2ac6d9)

This causes a huge performance slump and causes 3d web pages like Google Earth/Maps not being rendered properly.

I have reverted to Chromium version 125 and now I have hw acceleration.

![FireShot Capture 001 - GPU Internals - gpu](https://github.com/user-attachments/assets/60002d6c-2bff-4e2c-b353-61215c5de8db)

This is a huge issue and i hope somebody looks into it.

**Comment by XECDesign** [comment] 2024-09-12 22:17
Are you running under X or wayland?

**Comment by ghost** [comment] 2024-09-12 22:18
X11

**Comment by XECDesign** [comment] 2024-09-12 22:21
Last I heard that was a wontfix. Switching to labwc should fix it.

**Comment by ghost** [comment] 2024-09-12 22:34
Why was it broken in the first place? Why do we need to switch to wayland, wayland brings a less responsive desktop experience with it. I hate wayland. Is this a Chromium decision or is this a RPI decision to remove hw acceleration from it under x11? I don't understand this. What was the necessity for doing this?

**Comment by theofficialgman** [comment] 2024-09-13 15:46
> wayland brings a less responsive desktop experience with it.

@sudo-splinter-cell This is simply false and it is unfortunate that some users (like you) think it is the case instead of actually determining what their problem is. In some cases, users may find that their monitor/tv automatically configured resolution/framerate is different on a wayland desktop than an x11 desktop (for many reasons, all technical and different depending on the display server in use and video connection technology so too much to go into for this post).

So your first check should be that the wayland desktop of your choice is actually running at the native refresh rate of your display. Secondly, wayland (by design) always had VSYNC. This introduces some latency (especially on slower hardware) at the benefit of never tearing. In most cases though X11 VSYNC is enabled and the experience with Wayland with VSYNC will be no different.

Another thing that is VERY important is wayland is not a display server. It is a protocol that different display servers (eg: KDE KWIN, labwc, wayfire, GNOME Mutter, etc) implement. So the performance, bugs, etc are almost always specific to the particular display server in use.

I have seen your comments on the forum (https://forums.raspberrypi.com/viewtopic.php?p=2252692#p2252627) so I am already aware that you use KDE Plasma (aka: the KWIN display server and compositor) so if you have a particular issue with something not working as you expect under that implementation the correct location to check for open issues and open a new issue with constructive feedback would be here -> https://bugs.kde.org/ . One tip for KDE plasma has very configurable desktop effects, you will find one for "Show FPS" that can be helpful for analyzing KWIN's performance. Additionally, on Plasma up 5.27.X on Wayland and X11 there are "Compositor" settings you may want to try adjusting that affect when the compositor starts rendering and can reduce latency at the risk of occasionally missing a frame.

**Comment by ghost** [comment] 2024-09-13 16:04
Yeah thanks for the help. I am aware of most of what you say here. My frame rate is 60hz. I had the compositor disabled a long time ago and i actually "allow" screen tearing (at the cost of vsync), because i got used to my desktop being highly responsive, since windows 98 times, especially the mouse cursor. That mouse cursor responsiveness in wayland is probably just acceptable for most people, who are accustomed to touch screens or who just use high performance machines as their desktop which can provide high frame rates even under load. RPI 5 is not that kind of a machine. So "following the linux trend" in some cases maybe not the wise choice. I have tried to get used to it a couple times and every time i feel like i am "dragging" the actual mouse cursor along the screen with my mind, it is a frustrating experience. Trying to micro-manage mouse movements just to get the cursor to where it should be. And as you stated, because the frame rate is fixed, sometimes mouse cursor becomes "less visible" while moving, especially under gpu load and then i am putting more effort to follow where it is and where it will be.

These things might sound like childish complaints but if you use RPI-5 as a desktop, your experience will be the same. Some people might tolerate it, some might not. We are all different. I have been trying to test the new KDE (version 6) by installing some rolling distros (Manjaro for example) but it doesn't really bring anything different. There was some rumor about making the mouse cursor have a different layer of render to make it highly responsive even when other parts of the system are not, but i am yet to see it.

PS: I have already filed bug reports in regard to that "mouse cursor responsiveness" issue to KDE, RPI, Wayland, anywhere that is relevant, a long time ago. I feel like it is not being taken very seriously, as because it affects only us Pi users.

And this is why i think it is not a great idea to adopt wayland in slow hardware like ours. At least until some things are taken care of.

**Comment by theofficialgman** [comment] 2024-09-13 16:56
> PS: I have already filed bug reports in regard to that "mouse cursor responsiveness" issue to KDE, RPI, Wayland, anywhere that is relevant, a long time ago. I feel like it is not being taken very seriously, as because it affects only us Pi users.

I see no such OPEN issue reported regarding "mouse cursor responsiveness" on  https://bugs.kde.org/

> And this is why i think it is not a great idea to adopt wayland in slow hardware like ours. At least until some things are taken care of.

Your complaints to RPI LTD are unfounded about wayland. As I said, each display server implementation is different. Complaining about your KDE Plasma wayland experience to RPI LTD will go nowhere because its not their software and they have no control over it. RPI LTD builds and patches wayfire and labwc (now the preferred compositor) so if you have issues there then you can complain. Otherwise it is pointless.

> There was some rumor about making the mouse cursor have a different layer of render to make it highly responsive even when other parts of the system are not, but i am yet to see it.

Yes this is resolved with https://invent.kde.org/plasma/kwin/-/commit/4c397a95263d9c8e73d536ab1c2ac2caaeec60e2 (the commit linked resolved https://bugs.kde.org/show_bug.cgi?id=472663) (all Plasma 6 releases). On Kwin the cursor was always rendered on a separate plane however they were always synchronized to each other.  So if the desktop rendering was not hitting the frame target, the frame would be delayed, and the cursor would thus feel sluggish. Now (Plasma 6) they are independent and even if the primary plane is not done by the frame target (and thus needs to be delayed by a frame) the mouse position will still be updated.

If you have trouble still after than (ie: such as on a distro that ships Plasma 6) this is again an issue you should file on  https://bugs.kde.org/ . You will need to provide evidence though (ie: high framerate capture of your physical mouse motion with your monitor in the background under X11 and Wayland).

**Comment by ghost** [comment] 2024-09-13 17:16
Yeah i am currently downloading Fedora Rawhide which claims to have the latest (beta) version of KDE Plasma. It is the aarch64 version, but i am not sure if it will work on the Pi. We'll see. I will also test the latest RPIOS desktop. I had the same issues with RPIOS default desktop before when they first switched to wayland but let's see if anything has changed then.

**Comment by theofficialgman** [comment] 2024-09-13 17:36
> If you have trouble still after than (ie: such as on a distro that ships Plasma 6) this is again an issue you should file on https://bugs.kde.org/ . You will need to provide evidence though (ie: high framerate capture of your physical mouse motion with your monitor in the background under X11 and Wayland).

I've done this (on my Pi5 on labwc and PC on Wayland Plasma 6) and measured no difference compared to the baseline for my connected monitor (2-3 frames). The monitors (as tested by a 3rd party) input lag should be 1 frame. Now if the GPU load on the Pi5 is maxed out (due to some other process) then the entire labwc desktop drops frames (including the mouse) but that is likely because on labwc the mouse and primary plane rendering are tied together. Maybe thats not the case and its actually an issue with the hardware cursors implementation but I would expect that to affect both wayland and x11 (since both hardware cursor implementations rely on the same underlying hardware for functionality).

**Comment by ghost** [comment] 2024-09-13 17:44
You can imagine even the lightest webpages with a little bit of graphics will push the Pi to its limits, i mean even Spotify's main page for example, it is not an easy page to render for the Pi. So to get to that point that you mention is not really very hard for the Pi. Or even opening a Libreoffice document, seriously, that will take its toll on the Pi. I am not joking.

**Comment by XECDesign** [comment] 2024-09-16 11:05
Closing since OP deleted their account and the discussion got a bit derailed anyway.

No, we didn't intentionally break HW 3D acceleration on X11, but I don't know much much than that.

**Closed as not planned by XECDesign** 2024-09-16 11:05 UTC

**Comment by XECDesign** [comment] 2024-09-16 11:53
Just found that launching with `--use-angle=gles` makes WebGL work quite well.

And judging by `debian/patches/rpi/0012-Init-Prefer-GLES-to-everything-else-on-init.patch`, that should be the default behaviour, maybe I could take a look at what's happening there later.

**Comment by XECDesign** [comment] 2024-09-18 13:26
Should be fixed in today's release.
