### ISSUE TITLE
Right click and "search with google lens" returns "can't load this panel right now"

### ISSUE THREAD

**Issue by glanduin** [RPi-Distro/chromium-browser#49] opened 2024-10-11 21:28 UTC
If i right click on any picture/photo and click "search with google lens", the side panel (right side) loads with an error message which is this:

![Screenshot_20241012_002530](https://github.com/user-attachments/assets/65c24f32-d8b6-4e95-8137-88ea4b7a2b1c)

**Comment by XECDesign** [comment] 2024-10-16 15:23
I'm getting this with Debian's and Ubuntu's builds of the package as well, so I don't think this is caused by anything we've done. I suspect they will disable the feature in a later release. Closing for now since this is an upstream or debian bug.

**Closed as not planned by XECDesign** 2024-10-16 15:23 UTC
