### ISSUE TITLE
Chromium 92 issue

### ISSUE THREAD

**Issue by ChrisNic** [RPi-Distro/chromium-browser#33] opened 2022-05-24 22:35 UTC
i have a pi3b running buster using Chromium 92. it recognizes only my usb webcam not the picam. if i open caprine it sees both camera's. usb webcam has bad quality but built in mic. i can only video chat in messenger but would like to use other applications ie. telegram, meet, etc.
![Screenshot from 2022-05-23 22-02-09](https://user-images.githubusercontent.com/75809326/170143072-53a33a69-4654-49dd-a6ea-ebc893b701e5.png)
![Screenshot from 2022-05-23 22-07-10](https://user-images.githubusercontent.com/75809326/170143090-6eff1e3c-f24a-4eae-b2bc-7848a7186ee1.png)

**Comment by XECDesign** [comment] 2022-05-25 09:38
Duplicate of #23?

**Comment by XECDesign** [comment] 2022-05-25 09:40
Also, we don't support v92. We currently ship v101. If you're on buster, you're encouraged to switch to Debian's `chromium` package (rather than `chromium-browser`).

**Closed as not planned** 2024-09-11 14:23 UTC
